backend:
  name: git-gateway
  repo: dialoguetheory/atomic-mind
  branch: main # Branch to update
media_folder: "_site/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}