backend:
  name: git-gateway
  repo: dialoguetheory/atomic-mind
  branch: main # Branch to update
media_folder: "_site/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "home" # Used in routes, e.g., /admin/collections/blog
    label: "Home" # Used in the UI
    folder: "_pages/home" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}