backend:
  name: git-gateway
  repo: dialoguetheory/atomic-mind
  branch: main # Branch to update
media_folder: "_site/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Home"
    name: "home"
    editor:
      preview: false
    files:
      - label: "Sections"
        name: "sections"
        file: "_data/home.yml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero", name: "hero", widget: "markdown"}
          # - {label: "Section one title", name: "section-one-title", widget: "string"}
          # - {label: "section one content", name: "section-one-content", widget: "markdown"}
          # - {label: "Section one content", name: "section-one-image", widget: "image"}
          # - {label: "Section two title", name: "section-two-title", widget: "string"}
          # - {label: "section two content", name: "section-two-content", widget: "markdown"}
          # - {label: "Section two content", name: "section-two-image", widget: "image"}
          # - {label: "Section three title", name: "section-three-title", widget: "string"}
          # - {label: "section three content", name: "section-three-content", widget: "markdown"}
          # - {label: "Section three content", name: "section-three-image", widget: "image"}